fm_elfinder:
    assets_path: /assets
    instances:
#        default:
#            locale: en
#            editor: ckeditor
#            theme: smoothness
#            multi_home_folder: true
#            folder_separator: "|"
#            connector:
#                roots:
#                    uploads:
#                        driver: LocalFileSystem
#                        path: uploads/trash
#                        show_hidden: false
#                        upload_allow: ['none']
#                        upload_deny: ['all']
#                        upload_max_size: 2M
        form:
            locale: en
            editor: ckeditor
            theme: smoothness
            multi_home_folder: true
            folder_separator: "|"
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads/images/articles
                        show_hidden: false
                        upload_allow: [ 'image/png', 'image/jpg', 'image/jpeg', 'image/gif', 'image/webp' ]
                        upload_deny: [ 'all' ]
                        upload_max_size: 2M


