vich_uploader:
    db_driver: orm

    mappings:
        featured_images:
            uri_prefix: '%app.path.feature_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public%app.path.feature_images%'
        profile_images:
            uri_prefix: '%app.path.profile_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public%app.path.profile_images%'
